name: Sphinx Documentation Generator.

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3
        with:
          python-version: "3.8"

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Documentation
        run: |
          sphinx-apidoc -o docs airflow/
          cd docs
          make clean
          make html

      - name: Remove the venv folder
        run: |
          rm -rf venv

      - name: Commit and Push Changes
        run: |
          git config --local user.name "d-silva743"
          git config --local user.email "dom.silva@igt.com"
          git add .
          git commit -m "Update documentation"
          git push

      - name: Copy HTML files to gh-pages branch
        run: |
          git checkout --orphan gh-pages
          git rm -rf .
          cp -R docs/_build/html
          git add .
          git commit -m "Publish documentation to gh-pages branch"
          git push -f origin gh-pages

      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force_orphan: true
